import { User, Usage, Client, Message, Referral } from "@/lib/api";

// Helper to get dates relative to now
function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  return daysFromNow(-days);
}

export const DEMO_USER: User = {
  id: "demo-user",
  email: "sarah@remaxpremier.com",
  first_name: "Sarah",
  last_name: "Mitchell",
  phone_number: "+15125551234",
  company_name: "RE/MAX Premier",
  subscription_tier: "professional",
  subscription_status: "active",
  twilio_phone_number: "+15125559876",
};

export const DEMO_USAGE: Usage = {
  clients_count: 5,
  clients_limit: 100,
  messages_sent_this_month: 8,
};

export const DEMO_CLIENTS: Client[] = [
  {
    id: "demo-client-1",
    agent_id: "demo-user",
    first_name: "James",
    last_name: "Rodriguez",
    phone_number: "+15125551001",
    email: "james.r@email.com",
    property_address: "2847 Oak Creek Dr",
    city: "Austin",
    state: "TX",
    zip: "78745",
    property_type: "single_family",
    closing_date: daysAgo(450),
    engagement_score: 85,
    notes: "Great first-time buyer. Very responsive.",
    is_active: true,
    created_at: daysAgo(450),
  },
  {
    id: "demo-client-2",
    agent_id: "demo-user",
    first_name: "Emily",
    last_name: "Chen",
    phone_number: "+15125551002",
    email: "emily.chen@email.com",
    property_address: "1120 Barton Springs Rd #4B",
    city: "Austin",
    state: "TX",
    zip: "78704",
    property_type: "condo",
    closing_date: daysAgo(280),
    engagement_score: 72,
    notes: "Relocated from San Francisco. Works in tech.",
    is_active: true,
    created_at: daysAgo(280),
  },
  {
    id: "demo-client-3",
    agent_id: "demo-user",
    first_name: "Marcus",
    last_name: "Thompson",
    phone_number: "+15125551003",
    email: "marcus.t@email.com",
    property_address: "9301 Scenic Bluff Dr",
    city: "Austin",
    state: "TX",
    zip: "78733",
    property_type: "single_family",
    closing_date: daysAgo(120),
    engagement_score: 91,
    notes: "Second home purchase with me. Very loyal client.",
    is_active: true,
    created_at: daysAgo(120),
  },
  {
    id: "demo-client-4",
    agent_id: "demo-user",
    first_name: "Lisa",
    last_name: "Patel",
    phone_number: "+15125551004",
    email: "lisa.patel@email.com",
    property_address: "456 Congress Ave #12C",
    city: "Austin",
    state: "TX",
    zip: "78701",
    property_type: "condo",
    closing_date: daysAgo(60),
    engagement_score: 65,
    notes: "Investment property buyer. Interested in more.",
    is_active: true,
    created_at: daysAgo(60),
  },
  {
    id: "demo-client-5",
    agent_id: "demo-user",
    first_name: "David",
    last_name: "Kim",
    phone_number: "+15125551005",
    email: "david.kim@email.com",
    property_address: "7722 Manchaca Rd",
    city: "Austin",
    state: "TX",
    zip: "78748",
    property_type: "townhouse",
    closing_date: daysAgo(15),
    engagement_score: 50,
    notes: "Young couple, first home. Very excited.",
    is_active: true,
    created_at: daysAgo(15),
  },
];

export const DEMO_MESSAGES_SENT: Message[] = [
  {
    id: "demo-msg-s1",
    client_id: "demo-client-1",
    agent_id: "demo-user",
    message_text: "Hey James! Hope you're settling into 2847 Oak Creek Dr well! If you need any recommendations for contractors, landscapers, or anything else in Austin, don't hesitate to reach out. I'm always here for you! 🏡",
    message_type: "Week 1 Welcome",
    status: "delivered",
    scheduled_for: daysAgo(443),
    sent_at: daysAgo(443),
    client_first_name: "James",
    client_last_name: "Rodriguez",
    client_phone_number: "+15125551001",
  },
  {
    id: "demo-msg-s2",
    client_id: "demo-client-1",
    agent_id: "demo-user",
    message_text: "Hi James! How's the single family home treating you? It's been about a month since closing — hope everything's going great in Austin! Let me know if you need anything.",
    message_type: "Month 1 Check-in",
    status: "delivered",
    scheduled_for: daysAgo(420),
    sent_at: daysAgo(420),
    client_first_name: "James",
    client_last_name: "Rodriguez",
    client_phone_number: "+15125551001",
  },
  {
    id: "demo-msg-s3",
    client_id: "demo-client-2",
    agent_id: "demo-user",
    message_text: "Hey Emily! Hope you're settling into 1120 Barton Springs Rd well! Austin's an amazing city — let me know if you need any local recs. Always here for you! 🏡",
    message_type: "Week 1 Welcome",
    status: "delivered",
    scheduled_for: daysAgo(273),
    sent_at: daysAgo(273),
    client_first_name: "Emily",
    client_last_name: "Chen",
    client_phone_number: "+15125551002",
  },
  {
    id: "demo-msg-s4",
    client_id: "demo-client-1",
    agent_id: "demo-user",
    message_text: "Hi James! Quick update — Austin home values are up 4.2% this quarter. Great news for your investment! Let me know if you ever want a market analysis. 📈",
    message_type: "Month 6 Market Update",
    status: "delivered",
    scheduled_for: daysAgo(270),
    sent_at: daysAgo(270),
    client_first_name: "James",
    client_last_name: "Rodriguez",
    client_phone_number: "+15125551001",
    reply_text: "That's great to hear! Actually, my brother is looking to buy in the area. Can I give him your number?",
    reply_at: daysAgo(269),
    reply_read: true,
  },
  {
    id: "demo-msg-s5",
    client_id: "demo-client-3",
    agent_id: "demo-user",
    message_text: "Hey Marcus! Hope you're settling into 9301 Scenic Bluff Dr well! Such a beautiful property. Let me know if you need anything at all! 🏡",
    message_type: "Week 1 Welcome",
    status: "delivered",
    scheduled_for: daysAgo(113),
    sent_at: daysAgo(113),
    client_first_name: "Marcus",
    client_last_name: "Thompson",
    client_phone_number: "+15125551003",
    reply_text: "Thanks Sarah! We absolutely love it. Best decision we ever made!",
    reply_at: daysAgo(112),
    reply_read: true,
  },
  {
    id: "demo-msg-s6",
    client_id: "demo-client-2",
    agent_id: "demo-user",
    message_text: "Hi Emily! It's been 3 months — how's the condo treating you? Hope you're loving Austin! Let me know if any questions come up.",
    message_type: "Month 3 Check-in",
    status: "delivered",
    scheduled_for: daysAgo(190),
    sent_at: daysAgo(190),
    client_first_name: "Emily",
    client_last_name: "Chen",
    client_phone_number: "+15125551002",
  },
  {
    id: "demo-msg-s7",
    client_id: "demo-client-4",
    agent_id: "demo-user",
    message_text: "Hey Lisa! Hope you're settling into 456 Congress Ave well! What a great spot downtown. Let me know if you need anything! 🏡",
    message_type: "Week 1 Welcome",
    status: "delivered",
    scheduled_for: daysAgo(53),
    sent_at: daysAgo(53),
    client_first_name: "Lisa",
    client_last_name: "Patel",
    client_phone_number: "+15125551004",
  },
  {
    id: "demo-msg-s8",
    client_id: "demo-client-5",
    agent_id: "demo-user",
    message_text: "Hey David! Hope you and your wife are settling into 7722 Manchaca Rd well! Such an exciting time. If you need any recs for the neighborhood, I'm here! 🏡",
    message_type: "Week 1 Welcome",
    status: "delivered",
    scheduled_for: daysAgo(8),
    sent_at: daysAgo(8),
    client_first_name: "David",
    client_last_name: "Kim",
    client_phone_number: "+15125551005",
    reply_text: "Thanks so much Sarah! We're loving it. Our neighbor actually mentioned they might sell — interested?",
    reply_at: daysAgo(7),
    reply_read: false,
  },
];

export const DEMO_MESSAGES_UPCOMING: Message[] = [
  {
    id: "demo-msg-u1",
    client_id: "demo-client-5",
    agent_id: "demo-user",
    message_text: "Hi David! How's the townhouse treating you? It's been about a month since closing — hope everything's going great in Austin! Let me know if you need anything.",
    message_type: "Month 1 Check-in",
    status: "scheduled",
    scheduled_for: daysFromNow(15),
    client_first_name: "David",
    client_last_name: "Kim",
    client_phone_number: "+15125551005",
  },
  {
    id: "demo-msg-u2",
    client_id: "demo-client-4",
    agent_id: "demo-user",
    message_text: "Hi Lisa! It's been 3 months — how's the condo treating you? Hope you're loving the Congress Ave location! Let me know if any questions come up.",
    message_type: "Month 3 Check-in",
    status: "scheduled",
    scheduled_for: daysFromNow(30),
    client_first_name: "Lisa",
    client_last_name: "Patel",
    client_phone_number: "+15125551004",
  },
  {
    id: "demo-msg-u3",
    client_id: "demo-client-3",
    agent_id: "demo-user",
    message_text: "Hi Marcus! Quick update — Austin home values are up 3.8% this quarter. Great news for your investment on Scenic Bluff Dr! 📈",
    message_type: "Month 6 Market Update",
    status: "scheduled",
    scheduled_for: daysFromNow(60),
    client_first_name: "Marcus",
    client_last_name: "Thompson",
    client_phone_number: "+15125551003",
  },
  {
    id: "demo-msg-u4",
    client_id: "demo-client-5",
    agent_id: "demo-user",
    message_text: "Hey David! It's been 3 months — how's the townhouse treating you? Hope you and your wife are loving the neighborhood!",
    message_type: "Month 3 Check-in",
    status: "scheduled",
    scheduled_for: daysFromNow(75),
    client_first_name: "David",
    client_last_name: "Kim",
    client_phone_number: "+15125551005",
  },
  {
    id: "demo-msg-u5",
    client_id: "demo-client-2",
    agent_id: "demo-user",
    message_text: "Happy house-iversary, Emily! 🎉 Can you believe it's been a year since you moved to Barton Springs Rd? Hope Austin feels like home!",
    message_type: "Year 1 Anniversary",
    status: "scheduled",
    scheduled_for: daysFromNow(85),
    client_first_name: "Emily",
    client_last_name: "Chen",
    client_phone_number: "+15125551002",
  },
  {
    id: "demo-msg-u6",
    client_id: "demo-client-1",
    agent_id: "demo-user",
    message_text: "Hi James! Hope all is well in Austin. If anyone you know is thinking about buying or selling, I'd love to help — just send them my way!",
    message_type: "Month 18 Referral Nudge",
    status: "scheduled",
    scheduled_for: daysFromNow(95),
    client_first_name: "James",
    client_last_name: "Rodriguez",
    client_phone_number: "+15125551001",
  },
];

export const DEMO_REFERRALS: Referral[] = [
  {
    id: "demo-ref-1",
    agent_id: "demo-user",
    referred_by_client_id: "demo-client-1",
    referral_first_name: "Carlos",
    referral_last_name: "Rodriguez",
    referral_phone: "+15125552001",
    referral_email: "carlos.r@email.com",
    status: "qualified",
    notes: "James's brother. Looking for a 3BR in South Austin. Budget $450-500K.",
    created_at: daysAgo(268),
    referring_client_name: "James Rodriguez",
  },
  {
    id: "demo-ref-2",
    agent_id: "demo-user",
    referred_by_client_id: "demo-client-3",
    referral_first_name: "Nicole",
    referral_last_name: "Williams",
    referral_phone: "+15125552002",
    status: "contacted",
    notes: "Marcus's coworker. First-time buyer, interested in East Austin.",
    created_at: daysAgo(45),
    referring_client_name: "Marcus Thompson",
  },
  {
    id: "demo-ref-3",
    agent_id: "demo-user",
    referred_by_client_id: "demo-client-5",
    referral_first_name: "Tom",
    referral_last_name: "Anderson",
    referral_phone: "+15125552003",
    status: "new",
    notes: "David's neighbor who might be selling. Needs to chat about timing.",
    created_at: daysAgo(6),
    referring_client_name: "David Kim",
  },
];
